#!/bin/bash

out_dir="$PUBLISH_TO_DIR"
if [[ -z "$out_dir" ]] ; then
	out_dir="$HOME/pub/raw/windows-exe"
fi

mkdir -p "$out_dir"

# echo "Will publish your code into dir out_dir=$out_dir"
 
git_hash=$(git rev-parse HEAD)
git_hash_short=${git_hash:0:10}
git_branch=$(git rev-parse --abbrev-ref HEAD)
git_date=$(git show -s --format="%ci")
git_date_nice=$(date -u -d"${git_date}" +%Y%m%d_%H%M%S%z)
# echo "date=$git_date_nice"

filename_in="$1"
filename_out_dir="${git_date_nice}-${git_branch}-git${git_hash_short}"
filename_out_file="${filename_in}"

mkdir -p "$out_dir/$filename_out_dir/"

echo "$filename_in" "$out_dir/$filename_out_dir/$filename_out_file"
cp   "$filename_in" "$out_dir/$filename_out_dir/$filename_out_file" || { echo "Can not copy the file." ; exit 1; }


